apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - priority-classes.yaml
  - network-policies.yaml
  - services/api-gateway.yaml
  - services/order-matching-engine.yaml
  - services/trade-settlement-service.yaml
  - ingress/ingress.yaml
  - ingress/gateway.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: growww-platform
      compliance.growww.in/audit: "true"
