package main

import (
	"testing"
	"time"
)

func newTestFXProvider() *FXRateProvider {
	p := NewFXRateProvider(1 * time.Hour)
	_ = p.UpdateRate(FXRate{CurrencyUSD, CurrencyINR, 83.50, time.Now().UTC(), "REUTERS"})
	_ = p.UpdateRate(FXRate{CurrencyEUR, CurrencyUSD, 1.08, time.Now().UTC(), "BLOOMBERG"})
	_ = p.UpdateRate(FXRate{CurrencyGBP, CurrencyUSD, 1.27, time.Now().UTC(), "REUTERS"})
	return p
}

func TestComputeHaircutCashUSDtoINR(t *testing.T) {
	fxp := newTestFXProvider()
	calc := NewHaircutCalculator(fxp)

	result, err := calc.ComputeHaircut("HC-001", CollateralCash, CurrencyUSD, CurrencyINR, 100_000_00000000)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.FXRate != 83.50 {
		t.Errorf("expected FX rate 83.50, got %f", result.FXRate)
	}
	// Cash: base 0% + vol 0.5% + liq 0% + cross-currency vol addon 0.5% = 1.0%
	if result.TotalHaircutPct != 1.0 {
		t.Errorf("expected 1.0%% haircut, got %.2f%%", result.TotalHaircutPct)
	}
	if result.NetCollateralE8 == 0 {
		t.Error("net collateral should be > 0")
	}
	if result.ConvertedAmountE8 <= result.OriginalAmountE8 {
		t.Error("converted INR amount should be > original USD amount")
	}
}

func TestComputeHaircutCryptoHighHaircut(t *testing.T) {
	fxp := newTestFXProvider()
	calc := NewHaircutCalculator(fxp)

	// Same currency (USD->USD): no cross-currency addon
	_ = fxp.UpdateRate(FXRate{CurrencyUSD, CurrencyUSD, 1.0, time.Now().UTC(), "IDENTITY"})
	result, err := calc.ComputeHaircut("HC-002", CollateralCrypto, CurrencyUSD, CurrencyUSD, 50_000_00000000)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// Crypto: base 25% + vol 10% + liq 5% = 40% (no cross-currency addon)
	if result.TotalHaircutPct != 40.0 {
		t.Errorf("expected 40.0%% haircut, got %.2f%%", result.TotalHaircutPct)
	}
}

func TestComputeHaircutZeroAmountRejected(t *testing.T) {
	fxp := newTestFXProvider()
	calc := NewHaircutCalculator(fxp)

	_, err := calc.ComputeHaircut("HC-003", CollateralCash, CurrencyUSD, CurrencyINR, 0)
	if err == nil {
		t.Fatal("expected error for zero amount")
	}
}

func TestFXRateStalenessCheck(t *testing.T) {
	p := NewFXRateProvider(100 * time.Millisecond)
	_ = p.UpdateRate(FXRate{CurrencyUSD, CurrencyINR, 83.0, time.Now().Add(-1 * time.Second), "TEST"})

	_, err := p.GetRate(CurrencyUSD, CurrencyINR)
	if err == nil {
		t.Fatal("expected stale rate error")
	}
}

func TestFXRateIdentity(t *testing.T) {
	p := NewFXRateProvider(1 * time.Hour)
	rate, err := p.GetRate(CurrencyUSD, CurrencyUSD)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if rate.Rate != 1.0 {
		t.Errorf("identity rate should be 1.0, got %f", rate.Rate)
	}
}

func TestFXRateInverseAutoGenerated(t *testing.T) {
	p := NewFXRateProvider(1 * time.Hour)
	_ = p.UpdateRate(FXRate{CurrencyUSD, CurrencyINR, 83.50, time.Now().UTC(), "TEST"})

	rate, err := p.GetRate(CurrencyINR, CurrencyUSD)
	if err != nil {
		t.Fatalf("inverse rate not found: %v", err)
	}
	expected := 1.0 / 83.50
	diff := rate.Rate - expected
	if diff < -0.0001 || diff > 0.0001 {
		t.Errorf("inverse rate %.8f != expected %.8f", rate.Rate, expected)
	}
}

func TestUnsupportedCollateralType(t *testing.T) {
	fxp := newTestFXProvider()
	calc := NewHaircutCalculator(fxp)

	_, err := calc.ComputeHaircut("HC-004", CollateralType("ARTWORK"), CurrencyUSD, CurrencyINR, 100_00000000)
	if err == nil {
		t.Fatal("expected error for unsupported collateral")
	}
}
