name: growww_flutter
description: "Growww Sovereign Financial Workstation - Multi-Platform Mobile & Desktop Trading App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  crypto: ^3.0.7

dev_dependencies:
  test: ^1.24.0
